const textTranslationKeys: Record<string, string> = {
  "Account Information": "text.accountInformation",
  "Account": "text.account",
  "Active": "text.active",
  "Access Scope": "text.accessScope",
  "Add permission": "text.addPermission",
  "Admin": "navigation.admin",
  "Administration": "text.administration",
  "API base URL": "text.apiBaseUrl",
  "API Configuration": "text.apiConfiguration",
  "Assignment Analytics": "navigation.assignmentAnalytics",
  "Attendance": "navigation.attendance",
  "Avg. Completion": "text.avgCompletion",
  "Basic details linked to your account.": "text.basicAccountDetails",
  "Breakdown of students by gender.": "text.genderBreakdown",
  "Cancel": "common.cancel",
  "Category": "text.category",
  "Change filters or import Moodle data to see results.": "text.changeFilters",
  "Comfortable": "text.comfortable",
  "Compact": "text.compact",
  "Completion Rate": "text.completionRate",
  "Courses": "navigation.courses",
  "Course Analytics": "navigation.courseAnalytics",
  "Course List": "text.courseList",
  "Course name or short name": "text.courseSearchPlaceholder",
  "Courses ranked by total enrollments.": "text.coursesRanked",
  "Create role": "text.createRole",
  "Detailed breakdown by institution": "text.detailedBreakdownInstitution",
  "Dashboard density": "text.dashboardDensity",
  "Dashboard role": "text.dashboardRole",
  "Data visualization": "text.dataVisualization",
  "Date range": "text.dateRange",
  "Dark": "text.dark",
  "Department": "text.department",
  "Department Ranking": "text.departmentRanking",
  "Disable": "text.disable",
  "Display name": "text.displayName",
  "Distribution": "text.distribution",
  "Distribution of student login activity.": "text.loginActivityDistribution",
  "Email": "auth.email",
  "Email notifications": "text.emailNotifications",
  "Edit role": "text.editRole",
  "Export": "text.export",
  "Female": "text.female",
  "Female %": "text.femalePercent",
  "Gender": "text.gender",
  "Generate report": "text.generateReport",
  "Grade Analytics": "navigation.gradeAnalytics",
  "Hidden": "text.hidden",
  "Institution": "text.institution",
  "Invite user": "text.inviteUser",
  "Keep your account safe and protected.": "text.keepAccountSafe",
  "Learning Activity": "navigation.learningActivity",
  "Learning Performance": "navigation.learningPerformance",
  "Learning Analytics": "navigation.learningAnalytics",
  "Light": "text.light",
  "Loading analytics": "text.loadingAnalytics",
  "Male": "text.male",
  "Male %": "text.malePercent",
  "Manager": "text.manager",
  "Manage your account information and security settings.": "text.manageAccountSecurity",
  "Moodle Learning Analytics Report": "text.moodleLearningReport",
  "Next": "text.next",
  "No data available": "text.noDataAvailable",
  "Notifications": "common.notifications",
  "Partner": "text.partner",
  "Partner Requests": "navigation.partnerRequests",
  "Permission Matrix": "text.permissionMatrix",
  "Permission Model": "text.permissionModel",
  "Permission model": "text.permissionModel",
  "Please try again later.": "text.tryAgainLater",
  "Popular Courses": "text.popularCourses",
  "Preferences": "text.preferences",
  "Preview": "text.preview",
  "Privacy Policy": "text.privacyPolicy",
  "Preparing analytics data.": "text.preparingAnalytics",
  "Previous": "text.previous",
  "Profile Settings": "text.profileSettings",
  "Quiz Analytics": "navigation.quizAnalytics",
  "Rank": "text.rank",
  "Refresh": "text.refresh",
  "Reports": "navigation.reports",
  "Role Matrix": "text.roleMatrix",
  "Route metadata controls access": "text.routeMetadataControlsAccess",
  "Rows per page": "text.rowsPerPage",
  "Save Changes": "common.saveChanges",
  "Search": "common.search",
  "Search name, email, or username": "text.studentSearchPlaceholder",
  "Security": "text.security",
  "Settings": "navigation.settings",
  "Share": "text.share",
  "Something went wrong": "text.somethingWentWrong",
  "Status": "text.status",
  "Student activity": "text.studentActivity",
  "Student Analytics": "navigation.studentAnalytics",
  "Student Gender Distribution": "text.studentGenderDistribution",
  "Student Login Activity": "text.studentLoginActivity",
  "Students": "navigation.students",
  "System": "text.system",
  "Theme mode": "text.themeMode",
  "Terms & Conditions": "text.termsConditions",
  "Top courses": "text.topCourses",
  "Total": "text.total",
  "Total Courses": "text.totalCourses",
  "Total Students": "text.totalStudents",
  "Unable to load dashboard summary.": "text.unableLoadDashboard",
  "Unable to load live course charts.": "text.unableLoadCourseCharts",
  "Unable to load students.": "text.unableLoadStudents",
  "User": "text.user",
  "User Activity": "navigation.userActivity",
  "User Management": "navigation.userManagement",
  "User Profile": "text.userProfile",
  "View": "text.view",
  "Visible": "text.visible",
  "Visitor": "text.visitor",
  "Weekly digest": "text.weeklyDigest",
  "Workspace": "navigation.workspace",
};

export const useTranslateText = () => {
  const { t } = useI18n();

  const translateText = (value: unknown) => {
    if (typeof value !== "string") return value;

    const key = textTranslationKeys[value];

    return key ? t(key) : value;
  };

  return { translateText };
};
