const textTranslationKeys: Record<string, string> = {
  "Account Information": "text.accountInformation",
  "Account": "text.account",
  "Active": "text.active",
  "Active Students": "text.activeStudents",
  "Active Users": "text.activeUsers",
  "Actions": "text.actions",
  "Activities": "text.activities",
  "Activity rate": "text.activityRate",
  "Advanced Filters": "text.advancedFilters",
  "Access Scope": "text.accessScope",
  "Add permission": "text.addPermission",
  "Admin": "navigation.admin",
  "Administration": "text.administration",
  "All roles": "text.allRoles",
  "All statuses": "text.allStatuses",
  "API base URL": "text.apiBaseUrl",
  "API Configuration": "text.apiConfiguration",
  "Access types": "auth.accessTypes",
  "Account created successfully.": "auth.accountCreatedSuccessfully",
  "Add a short reason so the review decision is clear later.": "text.rejectPartnerRequestDescription",
  "Applied:": "text.applied",
  "Applied filters": "text.appliedFilters",
  "Applied course filters": "text.appliedCourseFilters",
  "Apply": "text.apply",
  "Apply filters": "text.applyFilters",
  "Apply search": "text.applySearch",
  "Approve": "text.approve",
  "Approved": "text.approved",
  "approved": "text.approved",
  "Applicant": "text.applicant",
  "Attendance": "navigation.attendance",
  "Back": "auth.back",
  "Back to login": "text.backToLogin",
  "Account & Institute Information": "auth.accountInstituteInformation",
  "Basic Information": "auth.basicInformation",
  "Basic details linked to your account.": "text.basicAccountDetails",
  "Breakdown of students by gender.": "text.genderBreakdown",
  "Cancel": "common.cancel",
  "Category": "text.category",
  "Categories": "text.categories",
  "City": "text.city",
  "Change filters or import Moodle data to see results.": "text.changeFilters",
  "Clear filters": "text.clearFilters",
  "Clear search": "text.clearSearch",
  "Close": "text.close",
  "Comfortable": "text.comfortable",
  "Compact": "text.compact",
  "Compare enrollment, snapshot engagement, and department coverage across institutes.": "text.compareEnrollmentAcrossInstitutes",
  "Compare total student records across institutes.": "text.compareStudentRecordsAcrossInstitutes",
  "Combine course, category, institute, and enrollment criteria.": "text.combineCourseFilters",
  "Combine date, institute, department, and user status.": "text.combineLearningActivityFilters",
  "Combine multiple criteria to update student records and analytics.": "text.combineStudentFilters",
  "Confirmed": "text.confirmed",
  "Course": "text.course",
  "Course Detail": "text.courseDetail",
  "Course ID": "text.courseId",
  "Course name": "text.courseName",
  "Course Summary": "text.courseSummary",
  "This summary explains what the grouped analytics course represents.": "text.courseSummaryDescription",
  "Courses": "navigation.courses",
  "Course Analytics": "navigation.courseAnalytics",
  "Course analytics": "navigation.courseAnalytics",
  "Course charts unavailable": "text.courseChartsUnavailable",
  "Course records are ready. Enrollment and view charts will update as Moodle analytics responds.": "text.loadingCourseChartsDescription",
  "Course groups": "text.courseGroups",
  "course groups": "text.courseGroups",
  "Course Views": "text.courseViews",
  "Course List": "text.courseList",
  "Course name or short name": "text.courseSearchPlaceholder",
  "Courses by Category": "text.coursesByCategory",
  "Courses by Enrollment": "text.coursesByEnrollment",
  "Courses by Institute": "text.coursesByInstitute",
  "Courses by institute half doughnut chart": "text.coursesByInstituteHalfDoughnutChart",
  "Courses ranked by total Moodle enrollment records.": "text.coursesByMoodleEnrollment",
  "Courses ranked by total enrollments.": "text.coursesRanked",
  "Create": "text.createRole",
  "Create Account": "auth.createAccount",
  "Create Partner Account": "auth.createPartnerAccount",
  "Create role": "text.createRole",
  "Choose State / Province": "auth.chooseStateProvince",
  "Detailed breakdown by institution": "text.detailedBreakdownInstitution",
  "Dashboard density": "text.dashboardDensity",
  "Dashboard role": "text.dashboardRole",
  "Data visualization": "text.dataVisualization",
  "Date range": "text.dateRange",
  "Date from": "text.dateFrom",
  "Date to": "text.dateTo",
  "Delete user": "text.deleteUser",
  "Delete user?": "text.deleteUserQuestion",
  "Delete": "text.delete",
  "This removes the Laravel application account. Moodle analytics data is not changed.": "text.deleteUserDescription",
  "Dark": "text.dark",
  "Department": "text.department",
  "Departments": "text.departments",
  "Department options follow the selected institute. Date filters apply to enrollment records, course counts, trends, and courses.": "text.departmentFilterExplanation",
  "Department Ranking": "text.departmentRanking",
  "Department Breakdown": "text.departmentBreakdown",
  "Student distribution inside this institute.": "text.departmentBreakdownDescription",
  "Difference": "text.difference",
  "Disable": "text.disable",
  "Display name": "text.displayName",
  "Distribution": "text.distribution",
  "Distribution of student login activity.": "text.loginActivityDistribution",
  "Edit": "text.edit",
  "Engagement": "text.engagement",
  "Engagement Summary": "text.engagementSummary",
  "Enrollment records": "text.enrollmentRecords",
  "Enrollments": "text.enrollments",
  "Enrollment Records": "text.enrollmentRecords",
  "Enrollment date from": "text.enrollmentDateFrom",
  "Enrollment date to": "text.enrollmentDateTo",
  "Login and account-status indicators for active/inactive student monitoring.": "text.studentActivityDescription",
  "Enrollment Trend": "text.enrollmentTrend",
  "Email": "auth.email",
  "Email notifications": "text.emailNotifications",
  "Edit role": "text.editRole",
  "Export": "text.export",
  "Export CSV": "text.exportCsv",
  "Excel file": "text.excelFile",
  "CSV file": "text.csvFile",
  "Female": "text.female",
  "Female %": "text.femalePercent",
  "Filter by user status": "text.filterByUserStatus",
  "Filter activity by city": "text.filterActivityByCity",
  "Filter activity by department": "text.filterActivityByDepartment",
  "Filter activity by institute": "text.filterActivityByInstitute",
  "Filter activity from date": "text.filterActivityFromDate",
  "Filter activity to date": "text.filterActivityToDate",
  "Filter institute analytics by department": "text.filterInstituteAnalyticsByDepartment",
  "Filter institute analytics by institute": "text.filterInstituteAnalyticsByInstitute",
  "Forum Activity": "text.forumActivity",
  "Gender": "text.gender",
  "Gender Distribution": "text.genderDistribution",
  "Generate report": "text.generateReport",
  "Google account verification is not configured.": "auth.googleVerificationNotConfigured",
  "Google account verified for partner registration.": "auth.googleAccountVerified",
  "Hidden": "text.hidden",
  "ID Card": "text.idCard",
  "ID card document": "text.idCardDocument",
  "I already have an account": "auth.alreadyHaveAccount",
  "High risk": "text.highRisk",
  "Inactive": "text.inactive",
  "Institution": "text.institution",
  "Institute": "text.institute",
  "Institute Information": "auth.instituteInformation",
  "Institute Detail": "text.instituteDetail",
  "Institute analytics": "text.instituteAnalytics",
  "Institutes Analytics": "text.institutesAnalytics",
  "Institutes": "text.institutes",
  "Institute Login Ranking": "text.instituteLoginRanking",
  "Institutes ranked by Moodle login volume, with active user context.": "text.institutesRankedByLoginVolume",
  "Institute Affiliation Document": "auth.instituteAffiliationDocument",
  "Inspect Moodle student records, demographics, and profile details.": "text.studentRecordsCopy",
  "Invite user": "text.inviteUser",
  "Keep your account safe and protected.": "text.keepAccountSafe",
  "Light": "text.light",
  "Low risk": "text.lowRisk",
  "Loading analytics": "text.loadingAnalytics",
  "Loading course charts": "text.loadingCourseCharts",
  "Loading student analytics charts": "text.loadingStudentAnalyticsCharts",
  "Loading student metric cards": "text.loadingStudentMetricCards",
  "Logins": "text.logins",
  "Analyze Moodle login trends, institute ranking, and student last-login status.": "text.moodleLoginMonitoringCopy",
  "Largest departments inside": "text.topDepartments",
  "Male": "text.male",
  "Male %": "text.malePercent",
  "Main Filters": "text.mainFilters",
  "Managers and visitors use system-wide access. Institute scope is only applied to partner accounts.": "text.managersVisitorsSystemWide",
  "Manager": "text.manager",
  "Manage platform and review partners": "auth.managePlatformReviewPartners",
  "Manage your account information and security settings.": "text.manageAccountSecurity",
  "Metric": "text.metric",
  "Medium risk": "text.mediumRisk",
  "Moodle course records": "text.moodleCourseRecords",
  "Moodle ID": "text.moodleId",
  "Moodle Profile Fields": "text.moodleProfileFields",
  "Read-only profile fields imported from Moodle.": "text.moodleProfileFieldsDescription",
  "Moodle student": "text.moodleStudent",
  "Moodle learning engagement": "text.moodleLearningEngagement",
  "Analyze cleaned Moodle courses by course name, category, institute, course-record count, and enrollment records.": "text.courseAnalyticsCopy",
  "Monthly enrollment records across the selected scope.": "text.enrollmentTrendDescription",
  "Month": "text.month",
  "Most Active Departments": "text.mostActiveDepartments",
  "Departments ranked by Moodle login volume, with active student context.": "text.departmentsRankedByLoginVolume",
  "More actions": "text.moreActions",
  "Name, email, or username": "text.nameEmailUsername",
  "Name, username, or email": "text.nameUsernameEmail",
  "Next": "text.next",
  "No chart data": "text.noChartData",
  "No data available": "text.noDataAvailable",
  "There are no non-zero values for this chart yet.": "text.noChartDataDescription",
  "No document uploaded": "text.noDocumentUploaded",
  "Not uploaded": "auth.notUploaded",
  "Not provided": "auth.notProvided",
  "Notifications": "common.notifications",
  "Overview": "text.overview",
  "Organization login grouping": "text.organizationLoginGrouping",
  "Original Course Name": "text.originalCourseName",
  "Original Moodle Courses": "text.originalMoodleCourses",
  "These are the original Moodle course records included in this cleaned course group.": "text.originalMoodleCoursesDescription",
  "Open file": "text.openFile",
  "Partner": "text.partner",
  "Partner Requests": "navigation.partnerRequests",
  "Partner access requests submitted from signup. Approval creates a Laravel system user with partner role.": "text.partnerRequestsDescription",
  "Partner request details": "text.partnerRequestDetails",
  "Review the signup information before approving institute access.": "text.partnerRequestDetailsDescription",
  "Permission Matrix": "text.permissionMatrix",
  "Permission Model": "text.permissionModel",
  "Permission model": "text.permissionModel",
  "Please try again later.": "text.tryAgainLater",
  "Popular Courses": "text.popularCourses",
  "Preferences": "text.preferences",
  "Preview": "text.preview",
  "Privacy Policy": "text.privacyPolicy",
  "Preparing analytics data.": "text.preparingAnalytics",
  "Previous": "text.previous",
  "Pending": "text.pending",
  "pending": "text.pending",
  "Phone": "text.phone",
  "Please choose a verified Google account.": "auth.chooseVerifiedGoogleAccount",
  "Please upload your institute affiliation document.": "auth.pleaseUploadAffiliationDocument",
  "Please verify your email by choosing a Google account.": "auth.pleaseVerifyGoogleEmail",
  "Passwords do not match.": "auth.passwordsDoNotMatch",
  "Province": "text.province",
  "Public or guest access": "auth.publicGuestAccess",
  "Profile Settings": "text.profileSettings",
  "Rank": "text.rank",
  "Requires Moodle log detail": "text.requiresMoodleLogDetail",
  "Reset password": "text.resetPassword",
  "Set a new Laravel application password for this user.": "text.resetPasswordDescription",
  "Resource usage": "text.resourceUsage",
  "risk": "text.risk",
  "Refresh": "text.refresh",
  "Reject": "text.reject",
  "Rejected": "text.rejected",
  "rejected": "text.rejected",
  "Reject partner request?": "text.rejectPartnerRequestQuestion",
  "Reject request": "text.rejectRequest",
  "Rejection reason:": "text.rejectionReason",
  "Reason": "text.reason",
  "Reports": "navigation.reports",
  "Role Matrix": "text.roleMatrix",
  "Route metadata controls access": "text.routeMetadataControlsAccess",
  "Rows per page": "text.rowsPerPage",
  "Review & Submit": "auth.reviewSubmit",
  "Request partner access for manager approval.": "auth.requestPartnerApproval",
  "Request partner access with your institute profile.": "auth.requestPartnerAccessProfile",
  "Submit Request": "auth.submitRequest",
  "Save Changes": "common.saveChanges",
  "Search": "common.search",
  "Search name or email": "text.searchNameOrEmail",
  "Search users": "text.searchUsers",
  "Search name, email, or institute": "text.searchNameEmailInstitute",
  "Search requests": "text.searchRequests",
  "Search name, email, or username": "text.studentSearchPlaceholder",
  "Search courses": "text.searchCourses",
  "Search institutes": "text.searchInstitutes",
  "Search students": "text.searchStudents",
  "Search students by name, username, or email": "text.searchStudentsByNameUsernameEmail",
  "Security": "text.security",
  "Select institute": "text.selectInstitute",
  "Short Name": "text.shortName",
  "Settings": "navigation.settings",
  "School / Institute": "auth.schoolInstituteName",
  "School / Institute Information": "auth.schoolInstituteInformation",
  "School / institute representative": "auth.schoolInstituteRepresentative",
  "Share": "text.share",
  "Something went wrong": "text.somethingWentWrong",
  "Status": "text.status",
  "Submitted": "text.submitted",
  "State / Province": "auth.stateProvince",
  "Student": "text.student",
  "Submit for Review": "auth.submitForReview",
  "Submit and manage institute data": "auth.submitManageInstituteData",
  "Student search": "text.studentSearch",
  "Search student activity": "text.searchStudentActivity",
  "Student activity": "text.studentActivity",
  "Student Analytics": "navigation.studentAnalytics",
  "Student Gender Distribution": "text.studentGenderDistribution",
  "Student List": "text.studentList",
  "Student Login Table": "text.studentLoginTable",
  "Students matching the current filters with last login details.": "text.studentLoginTableDescription",
  "Student Profile": "text.studentProfile",
  "Student Activity": "text.studentActivity",
  "Account status": "text.accountStatus",
  "Last activity": "text.lastActivity",
  "Last login": "text.lastLogin",
  "Not recorded": "text.notRecorded",
  "Yes": "text.yes",
  "No": "text.no",
  "No login activity recorded. This student should be prioritized for follow-up.": "text.neverLoggedInSummary",
  "Inactive account status. Review confirmation or suspension state before academic follow-up.": "text.inactiveAccountSummary",
  "Active account with recorded Moodle login activity.": "text.activeAccountSummary",
  "Student charts unavailable": "text.studentChartsUnavailable",
  "Student totals across all Moodle departments.": "text.studentsByDepartmentDescription",
  "Student totals across all Moodle institutes.": "text.studentsByInstituteDescription",
  "Student totals across reported cities.": "text.studentsByCityDescription",
  "Students": "navigation.students",
  "students": "navigation.students",
  "Students by City": "text.studentsByCity",
  "Students by Department": "text.studentsByDepartment",
  "Students by Institute": "text.studentsByInstitute",
  "System": "text.system",
  "System administrator access": "auth.systemAdministratorAccess",
  "System Users": "text.systemUsers",
  "Laravel application accounts for manager, partner, and visitor access.": "text.systemUsersDescription",
  "Theme mode": "text.themeMode",
  "Terms & Conditions": "text.termsConditions",
  "Total": "text.total",
  "Total Courses": "text.totalCourses",
  "Total Students": "text.totalStudents",
  "Top Departments": "text.topDepartments",
  "Course enrollment summary for this institute.": "text.topCoursesDescription",
  "Clean course analytics": "text.cleanCourseAnalytics",
  "Confirm password": "text.confirmPassword",
  "Course analytics sections": "text.courseAnalyticsSections",
  "Student analytics sections": "text.studentAnalyticsSections",
  "Institute analytics sections": "text.instituteAnalyticsSections",
  "Overview Filters": "text.overviewFilters",
  "Apply an institute scope to dashboard charts and choose the activity period.": "text.overviewFiltersDescription",
  "Clear institute filter": "text.clearInstituteFilter",
  "Create user": "text.createUser",
  "Create a Laravel application account.": "text.createUserDescription",
  "Edit user": "text.editUser",
  "Update a Laravel application account.": "text.updateUserDescription",
  "Role": "text.role",
  "New password": "text.newPassword",
  "Password": "text.password",
  "Save changes": "text.saveChanges",
  "Name": "text.name",
  "Grouped Moodle records": "text.groupedMoodleRecords",
  "No original Moodle course records found for this group.": "text.noOriginalMoodleCourses",
  "No department data is available for this institute.": "text.noDepartmentDataForInstitute",
  "No course enrollment data is available for this institute.": "text.noCourseEnrollmentDataForInstitute",
  "Updating departments for the selected institute...": "text.updatingDepartments",
  "Uploaded": "text.uploaded",
  "Uploaded by applicant": "text.uploadedByApplicant",
  "The student table is ready. Chart sections will update as Moodle analytics responds.": "text.loadingStudentAnalyticsChartsDescription",
  "Student totals will appear as soon as the Moodle analytics counts respond.": "text.loadingStudentMetricCardsDescription",
  "Unable to load dashboard summary.": "text.unableLoadDashboard",
  "Unable to load live course charts.": "text.unableLoadCourseCharts",
  "Unable to load students.": "text.unableLoadStudents",
  "Unable to verify Google account.": "auth.unableVerifyGoogleAccount",
  "Unable to verify institute affiliation.": "text.unableVerifyInstituteAffiliation",
  "Unable to load Google account verification.": "auth.unableLoadGoogleVerification",
  "Unable to submit partner request. Please check your details.": "auth.unableSubmitPartnerRequestCheck",
  "Unable to submit partner request. Please try again.": "auth.unableSubmitPartnerRequestTryAgain",
  "User": "text.user",
  "User status": "text.userStatus",
  "User Management": "navigation.userManagement",
  "User Profile": "text.userProfile",
  "You cannot delete your own account": "text.youCannotDeleteOwnAccount",
  "Your partner request was submitted.": "auth.partnerRequestSubmittedForReview",
  "Your partner request was submitted for Manager review.": "auth.partnerRequestSubmittedForReview",
  "View": "text.view",
  "View details": "text.viewDetails",
  "View limited dashboard information": "auth.viewLimitedDashboardInfo",
  "Visible": "text.visible",
  "Visitor": "text.visitor",
  "Week": "text.week",
  "Weekly digest": "text.weeklyDigest",
  "Where are the clean course groups concentrated?": "text.coursesByCategoryDescription",
  "Which clean courses have the most enrollments?": "text.coursesByEnrollmentDescription",
  "Which institutes appear most often in clean course groups?": "text.coursesByInstituteDescription",
  "Workspace": "navigation.workspace",
  "Year": "text.year",
  "Access summary": "text.accessSummary",
  "Read only": "text.readOnly",
  "Account snapshot": "text.accountSnapshot",
  "Report identity": "text.reportIdentity",
  "Password access": "text.passwordAccess",
  "Preference": "text.preference",
  "UI defaults": "text.uiDefaults",
  "Access scope": "text.accessScope",
  "All institutes and partner requests": "text.allInstitutesAndPartnerRequests",
  "Admin access": "text.adminAccess",
  "Manage all institutes": "text.manageAllInstitutes",
  "Assign partner accounts": "text.assignPartnerAccounts",
  "Approve or reject partner requests": "text.approveOrRejectPartnerRequests",
  "Manage institutes": "text.manageInstitutes",
  "Invite partner": "text.invitePartner",
  "Review requests": "text.reviewRequests",
  "Assigned institute": "text.assignedInstitute",
  "Active access": "text.activeAccess",
  "View assigned institute data": "text.viewAssignedInstituteData",
  "Update institute profile": "text.updateInstituteProfile",
  "Submit and review institute reports": "text.submitAndReviewInstituteReports",
  "Request access changes from a manager": "text.requestAccessChangesFromManager",
  "Request access change": "text.requestAccessChange",
  "View institute profile": "text.viewInstituteProfile",
  "Contact manager": "text.contactManager",
  "Public dashboard and basic profile": "text.publicDashboardAndBasicProfile",
  "Limited access": "text.limitedAccess",
  "View limited public dashboard data": "text.viewLimitedPublicDashboardData",
  "Update basic profile only": "text.updateBasicProfileOnly",
  "Institute reports and private data are locked": "text.instituteReportsLocked",
  "User management and approvals are locked": "text.userManagementLocked",
  "Request partner access": "text.requestPartnerAccess",
  "View public dashboard": "text.viewPublicDashboard",
  "Follow device setting": "text.followDeviceSetting",
  "Bright dashboard UI": "text.brightDashboardUi",
  "Low-light workspace": "text.lowLightWorkspace",
  "Bar": "text.bar",
  "Line": "text.line",
  "Pie": "text.pie",
  "Enabled": "text.enabled",
  "Username": "text.username",
  "Phone number": "text.phoneNumber",
  "Report signature": "text.reportSignature",
  "Discard changes?": "text.discardChangesQuestion",
  "Any unsaved account changes will be lost.": "text.unsavedChangesLost",
  "Keep editing": "text.keepEditing",
  "Discard": "text.discard",
  "Delete account?": "text.deleteAccountQuestion",
  "This is a destructive action and cannot be undone.": "text.destructiveActionWarning",
  "Deleting this account would remove profile details, preferences, and local session data.": "text.deleteAccountDescription",
  "Delete account": "text.deleteAccount",
  "Review the current account, dashboard defaults, and alert status.": "text.accountOverviewDescription",
  "Signed in as": "text.signedInAs",
  "Active account": "text.activeAccount",
  "Quick actions": "text.quickActions",
  "Jump to the settings that are changed most often.": "text.quickActionsDescription",
  "Edit profile": "text.editProfile",
  "Change password": "text.changePassword",
  "Appearance": "text.appearance",
  "Theme": "text.theme",
  "Choose dashboard color mode.": "text.chooseDashboardColorMode",
  "Manage the report identity shown in menus and exports.": "text.manageReportIdentity",
  "Profile details": "text.profileDetails",
  "These fields identify the account owner in menus and exports.": "text.profileDetailsDescription",
  "Profile preview": "text.profilePreview",
  "Shown in menus and exported reports.": "text.profilePreviewDescription",
  "Live": "text.live",
  "Protect access to Moodle analytics and local reports.": "text.protectAccessDescription",
  "Account protection": "text.accountProtection",
  "Password changes and two-factor authentication will be added here once backend verification is connected.": "text.securityComingSoon",
  "Reporting": "text.reporting",
  "Open each analytics page and export the visible dashboard data as CSV.": "text.reportsDescription",
  "CSV export available on feature pages": "text.csvExportAvailable",
  "Ready": "text.ready",
  "Open page": "text.openPage",
  "CSV export buttons are now placed inside the analytics feature pages next to the data they export.": "text.csvExportLocation",
  "Manage account overview, profile details, security, and appearance from one place.": "text.settingsDescription",
  "Control the default dashboard experience for your account.": "text.generalSettingsDescription",
  "General": "text.general",
  "Filter students by institute": "text.filterStudentsByInstitute",
  "Filter students by department": "text.filterStudentsByDepartment",
  "Filter students by city": "text.filterStudentsByCity",
  "Filter students by gender": "text.filterStudentsByGender",
  "Filter students by status": "text.filterStudentsByStatus",
  "Filter overview by institute": "text.filterOverviewByInstitute",
  "Filter login trend period": "text.filterLoginTrendPeriod",
  "Choose the login trend period for this institute.": "text.chooseLoginTrendPeriodForInstitute",
  "Apply a public institute scope and choose the login trend period.": "text.applyPublicInstituteScopeTrendPeriod",
  "Apply a public institute scope to dashboard charts.": "text.applyPublicInstituteScope",
  "filters": "text.filters",
  "activity rate": "text.activityRate",
  "courses": "navigation.courses",
  "Cambodia Higher Education Statistics": "text.cambodiaHigherEducationStatistics",
  "Explore public statistics about higher education institutions, student enrollment, and academic achievements across Cambodia.": "text.publicStatisticsDescription",
  "Loading scoped charts": "text.loadingScopedCharts",
  "Summary metrics are ready. Charts will appear when the analytics API responds.": "text.loadingScopedChartsDescription",
  "Charts unavailable": "text.chartsUnavailable",
};

export const useTranslateText = () => {
  const { t } = useI18n();

  const translateText = (value: unknown) => {
    if (typeof value !== "string") return value;

    const key = textTranslationKeys[value];

    return key ? t(key) : value;
  };

  return { translateText };
};
